create table customer (
    id BIGINT generated by default as Identity,
    name varchar(32),
    sex smallint,
    home_tel varchar(16),
    mobile_tel varchar(16),
    address varchar(200),
    primary key (id)
);

create table employee (
    id BIGINT generated by default as Identity,
    name varchar(32),
    sex smallint,
    home_tel varchar(16),
    mobile_tel varchar(16),
    address varchar(200),
    level smallint,
    primary key (id)
);

create table pet (
    id BIGINT generated by default as Identity,
    name varchar(32),
    sex smallint,
    category smallint,
    type smallint,
    blood_type smallint,
    master_id BIGINT,
    primary key (id),
    Constraint pet_fk foreign key (master_id)
        references customer (id) on update cascade on delete cascade
);