create table person (
    id BIGINT generated by default as Identity,
    name varchar(32),
    password varchar(64),
    sex smallint,
    home_tel varchar(16),
    mobile_tel varchar(16),
    address varchar(200),
    privilege smallint,
    primary key (id)
);


create table pet (
    id BIGINT generated by default as Identity,
    name varchar(32),
    sex smallint,
    category smallint,
    type smallint,
    blood_type smallint,
    master_id BIGINT,
    primary key (id),
    Constraint pet_fk foreign key (master_id)
        references person (id) on update cascade on delete cascade
);